export const AGREGAR_FERIADO = '[AGREGAR] Feriado'
export const EDITAR_FERIADO = '[EDITAR] Feriado'
export const LISTAR_FERIADO = '[LISTAR] Feriado'
export const BORRAR_FERIADO = '[LISTAR] Feriado'
export const AGREGAR_MATERIA = '[AGREGAR] Materia'
export const LISTAR_MATERIA = '[LISTAR] Materia'
export const LISTAR_UNIDAD = '[LISTAR] Unidad'
export const AGREGAR_UNIDAD = '[AGREGAR] Unidad'